#spring:
#  application:
#    name: eureka-server
#    version: test
#      -fcfd
#      -fbhsdbh
#
#server:
#  port: 8080


#nested
#more readable
#can use list
#boolean,string,number

#-----used technologies-------
#spring boot, kubernetes, docker, ci/cd pipeline

spring:
  application:
    name: eureka-server
    version: test

server:
  port: 8761

eureka:
  client:
    #server should not register itself as a service
    register-with-eureka: false
    #prevent fetching its own service list ( client list )
    fetch-registry: false


